services:
  # Main web service
  - type: web
    name: aorbo-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn aorbo_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: aorbo_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: aorbo-db
          property: connectionString

  # PostgreSQL database
  - type: postgres
    name: aorbo-db
    plan: free
    ipAllowList: []

databases:
  - name: aorbo-db
    databaseName: aorbo_db
    user: aorbo_user
    plan: free 