services:
  # Web Service
  - type: web
    name: aorbo-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn aorbo_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: aorbo_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: aorbo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /
    autoDeploy: true

  # PostgreSQL Database
  - type: postgres
    name: aorbo-db
    plan: free
    ipAllowList: [] 